name: UI CI
on:
  push:
    branches:
      - main
      - build
env:
  IMAGE: saferwall/ui
  VUE_APP_ANALYTICS_GOOGLE_TAG: UA-111524273-1
  VUE_APP_CSP_HOSTS: "*.saferwall.com saferwall.com"
  VUE_APP_BASE_URI: "https://saferwall.com/"
  VUE_APP_API_BASE_URL: "https://api.saferwall.com/v1/"
  VUE_APP_AVATAR_BASE_URL: "https://avatar.saferwall.com/"

jobs:
  yarn-build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build

  docker-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ env.IMAGE }}:latest
